name = "sami_tent_house"
main = "./dist/_worker.js"
compatibility_date = "2024-05-11"
account_id = "cfab4661433ad09f9e4c6be3e5362608" # From dashboard

[assets]
directory = "./dist"
binding = "ASSETS"  # Explicitly name the binding
not_found_handling = "single-page-application"
include = ["**/*"]

[vars]
CLOUDINARY_CLOUD_NAME = "dgauvdk6a"
CLOUDINARY_API_KEY = "999441443759723"
CLOUDINARY_API_SECRET = "Rh863jPaej_iPexJ90owWIXzbEc"